services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass senha123 --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - redis_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "senha123", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - redis_network

volumes:
  redis_data:
    driver: local
  redis_insight_data:
    driver: local

networks:
  redis_network:
    driver: bridge